### ISSUE TITLE
Mics Showing Above Player Heads?

### ISSUE THREAD

**Issue by blackjackph** [Vinzuerio/ph-enhanced#43] opened 2017-11-28 05:04 UTC
So microphone symbols are showing above player's heads, both Hunter and Props. I take it this is not supposed to be a feature as this is a game of hide and seek and that literally gives away a prop's location XD
Is there any way to fix this?

**Comment by Vinzuerio** [comment] 2017-11-28 06:24
duplicate of #6

**Closed by Vinzuerio** 2017-11-28 06:24 UTC

**Comment by blackjackph** [comment] 2017-11-28 18:47
Oh, sorry! I didn't even see that someone had already asked, my bad :3
