### ISSUE TITLE
Timer Failed! [RoundEndTimer]

### ISSUE THREAD

**Issue by hydrocut** [Vinzuerio/ph-enhanced#17] opened 2017-03-06 23:48 UTC
Hello,
I have a problem on my dedicated server

At each end of round by moment the hunter does not die and the round continues to infinity even if the chrono and rendered at 00:00

Timer Failed! [Simple][@gamemodes/fretta/gamemode/round_controller.lua (line 201)]

3. unknown - gamemodes/fretta/gamemode/round_controller.lua:201

I do not understand where it may come from
cordially

**Comment by Vinzuerio** [comment] 2017-03-07 05:55
Did you used any addons? Also which version of PH:E do you use

becausem I noticed on someone else that used Prop Hunt Taunt Pack Loader and it seems to be fails.

**Comment by hydrocut** [comment] 2017-03-07 09:58
I use several addons and I delete the taunt loader which allows to dapuier on F3 to have the direct taunt

But I still have an error on the round


Timer Failed! [RoundEndTimer][@gamemodes/fretta/gamemode/round_controller.lua (line 137)]

5. unknown - gamemodes/fretta/gamemode/round_controller.lua:137
4. RoundTimerEnd - gamemodes/prop_hunt/gamemode/init.lua:380
3. RoundEndWithResult - gamemodes/fretta/gamemode/round_controller.lua:167
2. SetRoundResult - addons/pointshop2/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:92
1. SetRoundResult - addons/pointshop2/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:42
[ERROR] addons/pointshop2/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:42: attempt to index upvalue 'teamPlayers' (a nil value)

List addons -:

Shoutvote
rubidium
raychamp_unstuck
powerround
prometheurs
poinshop2
altlaschat
ascorboard

**Comment by hydrocut** [comment] 2017-03-07 10:36
I just launched a blank server just with your gamemodes to test
Is the cause of the problem, I sent a ticket to the dev of poinshop 2

Poinshop 2 

Timer Failed! [RoundEndTimer][@gamemodes/fretta/gamemode/round_controller.lua (line 137)]

5. unknown - gamemodes/fretta/gamemode/round_controller.lua:137
4. RoundTimerEnd - gamemodes/prop_hunt/gamemode/init.lua:380
3. RoundEndWithResult - gamemodes/fretta/gamemode/round_controller.lua:167
2. SetRoundResult - addons/pointshop2/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:92
1. SetRoundResult - addons/pointshop2/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:42
[ERROR] addons/pointshop2/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:42: attempt to index upvalue 'teamPlayers' (a nil value)

**Comment by Vinzuerio** [comment] 2017-03-08 17:26
duplicate of #12 , Well it's better to contact pointshop 2 maker as this game has new hook function method instead having to use a custom fretta overrides.

**Closed by Vinzuerio** 2017-03-08 17:26 UTC
