### ISSUE TITLE
HUD, F1 menu missing textures

### ISSUE THREAD

**Issue by affirno** [Vinzuerio/ph-enhanced#62] opened 2018-05-14 19:28 UTC
After updating the new HUD and the F1 menu's are just missing textures and all the custom sounds no longer work.

**Comment by lucas2107** [comment] 2018-05-14 20:31
Update:

They are not auto downloaded.

**Comment by lucas2107** [comment] 2018-05-14 21:32
I think it's not included in the workshop 🤔

**Comment by affirno** [comment] 2018-05-14 23:37
They worked perfectly in the last version so i''m not sure. And if you're subscribed to it everything seems to work fine.

**Comment by Vinzuerio** [comment] 2018-05-15 05:09
Use/force the client by using `resource.AddWorkshop("417565863")`
This mostly caused by workshop not being updated properly.

Server: You have to Re-clone to latest commits version and replace everything. This should be fixed both client and server as well. Also delete the folder `addons/ph-enhanced` along with `materials,models, and sound` folder.

Content Notice:
If you're using/updating with the early version of Revision A (Not the latest patch of A.2), you may have to remove the `addons/ph-enhanced/` along with `materials, models, and sound` if present. This one causes to trouble having missing textures appeared, since the texture is now moved to the `gamemodes/prop_hunt/gamemode/content' instead.

**Comment by affirno** [comment] 2018-05-15 17:31
Everything seems to be working now. Thanks!

**Comment by affirno** [comment] 2018-05-15 19:46
Well its now randomly gone back to the same issue. Not sure what to do

**Comment by Vinzuerio** [comment] 2018-05-16 02:07
Was your workshop not properly being loaded btw? Always make sure to use `developer 2` when launching gmod, it must be workshop that not being properly loaded

**Comment by affirno** [comment] 2018-05-16 02:31
idk man, it worked fine at first but after the map changed it quit working. everything else works fine

**Comment by Vinzuerio** [comment] 2018-05-16 04:12
@lucas2107 how does on your side btw?

I might however going to re-test and what causing it didn't work at all, even though `resource.AddWorkshop()` is already included in.

**Comment by Vinzuerio** [comment] 2018-05-16 04:15
@affirno Also there is no console error happening after `developer 2` is enabled?

**Comment by Vinzuerio** [comment] 2018-05-17 08:06
@affirno By the mean having `developer 2` enabled in client side (which in your game), it will inform if there any failure download that has been made from Workshop and/or FastDL in the console (Press ~ to show this up). Usually if it fails, it will indicate what causes to fail, maybe it was caused by lost connection or something.

**Comment by Vinzuerio** [comment] 2018-05-18 11:55
Alright there should be a quick Revision B update shortly later tonight.

**Comment by Vinzuerio** [comment] 2018-05-18 14:29
Revision B has been released. Please check on both GitHub latest commit and Workshop as well. If anything works, please close the issue. Otherwise, always keep looking on the Console Errors.

**Closed** 2018-05-19 18:56 UTC
Labels: Need Investigation, addon-conflict, bug, client-issue
