### ISSUE TITLE
Custom Taunts don't go in F3

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#38] opened 2017-11-04 11:32 UTC
Hi,

Custom taunts are not working in F3 because you don't use the same table in init.lua and in prop_taunts.lua

Use PHE.PH_TAUNT_CUSTOM.PROP
instead of PHE.PROPS_TAUNTS

**Comment by daunknownman2010** [comment] 2017-11-05 04:09
This is by design as the implementation of ShowSpare (F3) accounts for the **ph_enable_custom_taunts** convar. When the convar returns 0, it falls back to original Prop Hunt taunting which shouldn't include the additional custom taunts the gamemode can make use of.

**Comment by lucas2107** [comment] 2017-11-05 13:51
ph_enable_custom_taunts 2

That's what I've in my config

**Comment by daunknownman2010** [comment] 2017-11-08 10:09
Alright, looked over that part. Re-opening and may possibly look into it later.

**Comment by Vinzuerio** [comment] 2017-11-08 12:45
There was a change with ph_enable_custom_taunts convar which it should be integer instead a boolean value.

**Comment by Chillstice** [comment] 2018-03-24 05:00
FTFY
\garrysmod\gamemodes\prop_hunt\gamemode\init.lua line 356
`-- Called when player presses [F3]. Plays a taunt for their team
function GM:ShowSpare1(pl)
	-- if GetConVar("ph_enable_custom_taunts"):GetBool() && GAMEMODE:InRound() then
	if (GetConVar("ph_enable_custom_taunts"):GetInt() == 1) && GAMEMODE:InRound() then
		pl:ConCommand("ph_showtaunts")
	end
	
	--if !GetConVar("ph_enable_custom_taunts"):GetBool() && GAMEMODE:InRound() && pl:Alive() && (pl:Team() == TEAM_HUNTERS || pl:Team() == TEAM_PROPS) && pl.last_taunt_time + PHE.TAUNT_DELAY <= CurTime() && #PHE.PROP_TAUNTS > 1 && #PHE.HUNTER_TAUNTS > 1 then
	if ((GetConVar("ph_enable_custom_taunts"):GetInt() == 0) or (GetConVar("ph_enable_custom_taunts"):GetInt() == 2)) && GAMEMODE:InRound() && pl:Alive() && (pl:Team() == TEAM_HUNTERS || pl:Team() == TEAM_PROPS) && pl.last_taunt_time + PHE.TAUNT_DELAY <= CurTime() && #PHE.PROP_TAUNTS > 1 && #PHE.HUNTER_TAUNTS > 1 then
		repeat
			if pl:Team() == TEAM_HUNTERS then
				--rand_taunt = table.Random(PHE.HUNTER_TAUNTS)
				merge_hunter_tables = table.merge(PHE.HUNTER_TAUNTS, PHE.PH_TAUNT_CUSTOM.HUNTER)
				rand_taunt = table.Random(merge_hunter_tables)
			else
				--rand_taunt = table.Random(PHE.PROP_TAUNTS)
				merge_prop_tables = table.merge((PHE.PROP_TAUNTS), (PHE.PH_TAUNT_CUSTOM.PROP))
				rand_taunt = table.Random(merge_prop_tables)
			end
		until rand_taunt != pl.last_taunt
		
		pl.last_taunt_time = CurTime() + PHE.TAUNT_DELAY
		pl.last_taunt = rand_taunt
		
		pl:EmitSound(rand_taunt, 100)
		pl:SendLua("LocalPlayer().last_taunt_time = CurTime()")
	end	
end

function table.merge(t1, t2)
   for k,v in ipairs(t2) do
      table.insert(t1, v)
   end 
 
   return t1
end`

Merge the two tables using a new function, move the merged table to a new variable, pick random element to play from merged table.

**Comment by Vinzuerio** [comment] 2018-05-12 10:49
Custom Taunts will be listed into 'Custom/PH: Enhanced' taunt list, and it will be appear on Taunt Window. It is also will be played on Random Taunt and Auto-Taunt as well.

**Closed by Vinzuerio** 2018-05-12 10:49 UTC
